version: '3'
services:
  db:
    hostname: db
    image: postgres:9.6
    ports:
      - "5432:5432"
    volumes:
      - .:/code
      - ./compose/postgres/postgresql_init_scripts:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_PASSWORD=postgres


  web:
    build:
      context: .
      dockerfile: compose/django/Dockerfile
      args:
        USER_ID: 1000
        USER_GROUP: 1000
    tty: true
    command: /start
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.dev
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PORT=5432
      - DATABASE_URL=postgres://postgres:postgres@db/postgres
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
