# Generated by Django 3.0.7 on 2020-12-08 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drawings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='body',
            old_name='projection',
            new_name='projection_plane',
        ),
    ]
